  
spring:
  datasource:  
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3308/Transportadora?useTimezone=TRUE&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
